sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 
    port: 20473
    database: sky_take_out
    username: 
    password: 
  redis:
    host: localhost
    port: 
    password: 
    database: 0
  wechat:
    appid: 
    secret: 
    mchid: 
