sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: sh-cynosdbmysql-grp-hk8b7n4g.sql.tencentcdb.com
    port: 20473
    database: sky_take_out
    username: lqj
    password: LQJ123456@
#  alioss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
#    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
#    bucket-name: sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx418061ce6c337d49
    secret: 8e980be44041cbf07ccc14dcc86b0ed0
    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: D:\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
#    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
